# Generated by Django 5.0.6 on 2024-06-29 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_at', models.DateTimeField(auto_now_add=True, verbose_name='구매 시각')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='개수')),
                ('price_per_medicine_at_purchase', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='구매 당시 하나 당 가격')),
                ('medicine', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='medicines.medicine', verbose_name='약')),
            ],
        ),
    ]
