# Generated by Django 5.0.6 on 2024-05-31 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='user',
            new_name='owner',
        ),
    ]
