# Generated by Django 5.0.6 on 2024-05-31 04:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_rename_user_receipt_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='price_per_medicine_at_purchase',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='receipt',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
