# Generated by Django 5.0.6 on 2024-05-31 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_alter_receipt_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='price_per_medicine_at_purchase',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='하나당 가격'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='개수'),
        ),
    ]
