# Generated by Django 5.0.6 on 2024-05-31 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_alter_receipt_price_per_medicine_at_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='price_per_medicine_at_purchase',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='구매 당시 하나 당 가격'),
        ),
    ]
