# Generated by Django 5.0.6 on 2024-05-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_receipt_price_per_medicine_at_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='created_at',
            new_name='purchase_at',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='updated_at',
        ),
    ]
