# Generated by Django 5.0.6 on 2024-05-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='detail',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
