# Generated by Django 5.0.6 on 2024-06-29 10:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='medicines.medicine')),
            ],
            options={
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
