# Generated by Django 5.0.6 on 2024-06-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnose',
            options={'verbose_name_plural': 'Diagnosis'},
        ),
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Queries'},
        ),
        migrations.AddField(
            model_name='diagnose',
            name='title',
            field=models.CharField(default='Untitled', max_length=50),
        ),
        migrations.AlterField(
            model_name='query',
            name='diagnose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='diagnosis.diagnose'),
        ),
    ]
