# Generated by Django 5.0.6 on 2024-06-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_alter_diagnose_options_alter_query_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='title',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
