# Generated by Django 5.0.6 on 2024-05-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.PositiveBigIntegerField(unique=0)),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(default='', max_length=150)),
                ('main_ingredient', models.TextField(blank=True, default='')),
                ('efficacy', models.TextField(blank=True, default='')),
                ('usage', models.TextField(blank=True, default='')),
                ('need_to_know', models.TextField(blank=True, default='')),
                ('cautions', models.TextField(blank=True, default='')),
                ('beware_food', models.TextField(blank=True, default='')),
                ('side_effect', models.TextField(blank=True, default='')),
                ('how_to_store', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
