# Generated by Django 5.0.6 on 2024-05-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='beware_food',
            field=models.TextField(blank=True, default='', verbose_name='이 약을 사용하는 동안 주의해야 할 약 또는 음식은 무엇입니까?'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='cautions',
            field=models.TextField(blank=True, default='', verbose_name='이 약의 사용상 주의사항은 무엇입니까?'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='company',
            field=models.CharField(default='', max_length=150, verbose_name='업체명'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='efficacy',
            field=models.TextField(blank=True, default='', verbose_name='이 약의 효능은 무엇입니까?'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='how_to_store',
            field=models.TextField(blank=True, default='', verbose_name='이 약은 어떻게 보관해야 합니까?'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='main_ingredient',
            field=models.TextField(blank=True, default='', verbose_name='주성분'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=150, verbose_name='제품명'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='need_to_know',
            field=models.TextField(blank=True, default='', verbose_name='이 약을 사용하기 전에 반드시 알아야 할 내용은 무엇입니까?'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='serial_number',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='품목일련번호'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='side_effect',
            field=models.TextField(blank=True, default='', verbose_name='이 약은 어떤 이상반응이 나타날 수 있습니까?'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='usage',
            field=models.TextField(blank=True, default='', verbose_name='이 약은 어떻게 사용합니까?'),
        ),
    ]
