# Generated by Django 5.0.6 on 2024-06-29 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(default=8500, validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='remaining',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='개수'),
        ),
    ]
