# Generated by Django 5.0.6 on 2024-05-26 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medicines",
            "0002_alter_medicine_beware_food_alter_medicine_cautions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="medicine",
            name="price",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="가격",
            ),
        ),
    ]
