# Generated by Django 5.0.6 on 2024-06-29 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_alter_medicine_price_alter_medicine_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.PositiveIntegerField(default=2500, validators=[django.core.validators.MinValueValidator(0)], verbose_name='가격'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='remaining',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='개수'),
        ),
    ]
