# Generated by Django 5.0.6 on 2024-07-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_alter_medicine_price_alter_medicine_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
